# Generated by Django 5.2.3 on 2026-03-27 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cars/')),
                ('max_speed', models.IntegerField()),
                ('engine', models.CharField(max_length=100)),
                ('charging_port', models.CharField(max_length=100)),
                ('maintenance_cycle', models.CharField(max_length=50)),
                ('seat_capacity', models.IntegerField()),
                ('audio_system', models.CharField(max_length=100)),
                ('battery_percentage', models.IntegerField(default=0)),
                ('is_charging', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
